"""Build the offline English presentation dictionary, preserving source evidence."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
FIELDS = {'title', 'object', 'proposition', 'text', 'note', 'label', 'coverage_note'}

def render(root=ROOT, documents=None):
    source = root / 'data/i18n/en.json'
    translations = json.loads(source.read_text())
    if not all(isinstance(k, str) and k and isinstance(v, str) and v for k, v in translations.items()):
        raise ValueError('Empty or invalid translation')
    def check(value, key=None):
        if key in {'evidence', 'simple'}:
            return
        if isinstance(value, dict):
            for k, v in value.items():
                check(v, k)
        elif isinstance(value, list):
            for v in value:
                check(v)
        elif key in FIELDS and isinstance(value, str) and value not in translations:
            raise ValueError('Missing English interpretation: ' + value)
    if documents is None:
        documents = json.loads((root / 'data/qualified_opinions.json').read_text())['documents']
    check(documents)
    payload = ('/* Generated by scripts/build_translations.py */\nwindow.SITE_EN = ' +
               json.dumps(translations, ensure_ascii=False, sort_keys=True) + ';\n').encode()
    return {'docs/assets/english.js': payload,
            'data/i18n/en.json': source.read_bytes(),
            'docs/data/i18n/en.json': source.read_bytes()}

if __name__ == '__main__':
    for name, content in render().items():
        path = ROOT / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
