"""Reproducible release pipeline. Python 3.10+, standard library only.

Canonical inputs live in data/source/. Nothing generated is read as a source.
Build in memory, validate, then publish with rollback on ordinary I/O failures.
"""
from __future__ import annotations
import argparse
import copy
import csv
import datetime as dt
import hashlib
import io
import json
import os
from pathlib import Path
import re
import tempfile
import zipfile

# Files that make up the published dataset (data/ and the download archive); docs/data/ holds everything the site loads.
DATASET_FILES = ('documentary.csv', 'analytical.csv', 'hypotheses.csv', 'units.json', 'qualified_opinions.json',
                 'abbreviations.csv', 'names_authority.csv', 'SCHEMA.md', 'PROVENANCE.md', 'release.json')
from ner import EntityRecognizer, extract_corpus
from entity_context import build_contexts
from reasoning import extract_corpus as extract_reasoning
from opinion_extraction import extract_corpus as extract_opinion_frames
from qualified_opinions import build as build_qualified_opinions
from review_packets import ANCHOR_COLUMNS, finite_metric, hypothesis_key, validate_anchor

ROOT = Path(__file__).resolve().parents[1]
# Extent of the legacy working index, NOT the physical size of the register.
TOTAL = 192
FEATURES = ['policy_domain', 'decision_orientation', 'document_trigger', 'actors',
            'geography', 'risk_terms', 'fiscal_terms', 'institutional_terms',
            'monetary_expressions', 'deontic_formulas']
CLASSIFIERS = FEATURES[:3]
FMAP = {**{k: k for k in FEATURES}, 'person': 'actors', 'place': 'geography',
        'term_fiscal': 'fiscal_terms', 'term_deontic': 'deontic_formulas',
        'term_institutions': 'institutional_terms', 'term_monetary': 'monetary_expressions',
        'fiscal_term': 'fiscal_terms', 'deontic_formula': 'deontic_formulas',
        'institutional_term': 'institutional_terms', 'monetary_expression': 'monetary_expressions'}
UNCERTAINTY = {'present', 'absent', 'not_visible', 'not_transcribed', 'not_checked', 'uncertain', 'not_applicable'}
TSTATUS = {'manual', 'manual_full', 'manual_partial', 'regest', 'not_transcribed', 'htr_raw', 'htr_aligned', 'reviewed'}
RELTYPES = {'none', '', 'dissent_to', 'continuation_of', 'continuation', 'copy_of',
            'repeated_supplication', 'same_dossier_as', 'response_to', 'correction_of', 'corrected_by'}
DOC_COLS = ['register_id', 'unit_id', 'folio_start', 'folio_end', 'folio_raw', 'foliation_status', 'foliation_note', 'date_original', 'date_iso',
            'date_precision', 'marginal_note_raw', 'marginal_note_present', 'signatories_raw',
            'signatories_norm', 'signatory_count', 'signatories_complete', 'text_diplomatic',
            'transcription_status', 'relation_type', 'related_unit_id', 'relation_status',
            'relation_source', 'date_check', 'regest_note', 'uncertain_readings', 'validation_status']
ANA_COLS = ['unit_id'] + FEATURES + [k + '_status' for k in FEATURES] + [k + '_review_status' for k in FEATURES]
HYP_COLS = ['unit_id', 'feature', 'value', 'rule', 'confidence', 'evidence', 'decision', 'new_value', 'reviewer', 'reviewed_at'] + ANCHOR_COLUMNS
CER_REVIEW_THRESHOLD = 0.15
WER_REVIEW_THRESHOLD = 0.40


def json_bytes(obj):
    return (json.dumps(obj, ensure_ascii=False, indent=2, allow_nan=False) + '\n').encode('utf-8')


def csv_bytes(rows, columns):
    out = io.StringIO(newline='')
    writer = csv.DictWriter(out, fieldnames=columns, extrasaction='ignore', lineterminator='\n')
    writer.writeheader()
    writer.writerows(rows)
    return out.getvalue().encode()


def read_csv(path):
    with path.open(encoding='utf-8-sig', newline='') as stream:
        return list(csv.DictReader(stream))


def js_bytes(name, value):
    return ('// Generated by scripts/pipeline.py; do not edit.\nwindow.' + name + '=' +
            json.dumps(value, ensure_ascii=False).replace('</', '<\\/') + ';\n').encode()


def normalize_hyp(rows):
    result = []
    for row in rows:
        r = {k: str(row[k]) if row.get(k) is not None else '' for k in HYP_COLS}
        r['feature'] = row.get('feature') or row.get('field', '')
        r['rule'] = row.get('rule') or row.get('rule_id', '')
        result.append(r)
    return result


def load_sources(root):
    return (json.loads((root / 'data/source/units.json').read_text(encoding='utf-8')),
            normalize_hyp(read_csv(root / 'data/source/hypotheses.csv')))


def audit_transcriptions(units):
    """Run deterministic structural and HTR quality checks on source readings.

    These checks identify passages that need an expert image comparison; they do
    not assert that a diplomatic reading is philologically correct.
    """
    rows = []
    flag_counts = {}
    status_counts = {}
    for unit in units:
        uid = unit.get('unit_id', '')
        status = unit.get('transcription_status', '')
        text = unit.get('text_diplomatic') or ''
        flags = []
        if status.startswith('manual') and not text.strip():
            flags.append('missing_text')
        if status == 'manual_partial':
            flags.append('partial_transcription')
        if status == 'regest':
            flags.append('regest_only')
        if '(?)' in text or '??' in text:
            flags.append('uncertain_reading')
        if text.count('[') != text.count(']') or text.count('(') != text.count(')'):
            flags.append('unbalanced_brackets')
        if re.search(r'\s{2,}', text):
            flags.append('repeated_whitespace')
        if any(ord(ch) < 32 and ch not in '\n\r\t' for ch in text):
            flags.append('control_character')
        cer, wer = unit.get('cer'), unit.get('wer')
        if isinstance(cer, (int, float)) and cer >= CER_REVIEW_THRESHOLD:
            flags.append('high_cer')
        if isinstance(wer, (int, float)) and wer >= WER_REVIEW_THRESHOLD:
            flags.append('high_wer')
        for flag in flags:
            flag_counts[flag] = flag_counts.get(flag, 0) + 1
        status_counts[status] = status_counts.get(status, 0) + 1
        actionable = [f for f in flags if f != 'regest_only']
        priority = ('high' if any(f in actionable for f in ('missing_text', 'unbalanced_brackets', 'control_character', 'high_cer', 'high_wer'))
                    else 'medium' if actionable else 'info' if flags else 'ok')
        rows.append(dict(unit_id=uid, transcription_status=status, chars=len(text),
                         words=len(re.findall(r"\S+", text)), cer=cer, wer=wer,
                         flags=flags, priority=priority, review_required=bool(actionable)))
    evaluated = [r for r in rows if isinstance(r['cer'], (int, float)) and isinstance(r['wer'], (int, float))]
    summary = dict(total_units=len(rows), status_counts=dict(sorted(status_counts.items())),
                   manual_units=sum(count for status, count in status_counts.items() if status.startswith('manual')),
                   regest_units=status_counts.get('regest', 0), evaluated_units=len(evaluated),
                   flagged_units=sum(r['review_required'] for r in rows),
                   high_priority_units=sum(r['priority'] == 'high' for r in rows),
                   flag_counts=dict(sorted(flag_counts.items())),
                   mean_cer=round(sum(r['cer'] for r in evaluated) / len(evaluated), 4) if evaluated else None,
                   mean_wer=round(sum(r['wer'] for r in evaluated) / len(evaluated), 4) if evaluated else None,
                   max_cer=max((r['cer'] for r in evaluated), default=None),
                   max_wer=max((r['wer'] for r in evaluated), default=None))
    return dict(schema_version=1,
                thresholds=dict(cer_review=CER_REVIEW_THRESHOLD, wer_review=WER_REVIEW_THRESHOLD),
                summary=summary, units=rows,
                note='Automated structural and HTR metric checks identify passages for image comparison; they do not prove philological correctness.')


def folio_sides(start, end=''):
    """Inclusive recto/verso interval; an unsided folio includes both sides."""
    def pos(s, is_end):
        m = re.fullmatch(r'([1-9]\d*)([rv]?)', s)
        if not m or not 1 <= int(m[1]) <= TOTAL:
            raise ValueError('Invalid folio: ' + repr(s))
        return (int(m[1]) - 1) * 2 + (1 if m[2] == 'v' or (not m[2] and is_end) else 0)
    a, b = pos(start, False), pos(end or start, True)
    if b < a:
        raise ValueError('Reversed folio range')
    return [f'{n // 2 + 1}{"rv"[n % 2]}' for n in range(a, b + 1)]


def validate_sources(root, source, hypotheses):
    errors = []
    foliation_review = source.get('meta', {}).get('foliation_review')
    if foliation_review is not None and (
            foliation_review.get('status') != 'unreconciled'
            or foliation_review.get('reference_system') != 'legacy_working_references'
            or not foliation_review.get('note')):
        errors.append('Invalid foliation_review: unresolved working references require a note')
    units = source.get('units', [])
    ids = [u.get('unit_id', '') for u in units]
    if not ids or len(ids) != len(set(ids)):
        errors.append('Unit IDs must be nonempty and unique')
    for u in units:
        uid = u.get('unit_id', '')
        for metric in ('cer', 'wer'):
            if u.get(metric) is not None:
                try:
                    finite_metric(u[metric], metric)
                except ValueError as exc:
                    errors.append(f'{uid}: {exc}')
        if not re.fullmatch(r'R142_\d{4}', uid):
            errors.append(f'Invalid unit ID: {uid}')
        if u.get('transcription_status') not in TSTATUS:
            errors.append(f'{uid}: invalid transcription_status')
        sides = u.get('folio_sides', [])
        if not sides and (u.get('foliation_status') != 'uncertain' or not u.get('foliation_note')):
            errors.append(f'{uid}: missing folio_sides requires explicit uncertainty and note')
        if len(sides) != len(set(sides)):
            errors.append(f'{uid}: duplicate folio sides')
        for side in sides:
            if not re.fullmatch(r'[1-9]\d*[rv]', side) or not 1 <= int(side[:-1]) <= TOTAL:
                errors.append(f'{uid}: invalid folio side {side}')
        date = u.get('date_iso', '')
        if date:
            try:
                if not re.fullmatch(r'\d{4}(-\d{2}(-\d{2})?)?', date):
                    raise ValueError()
                dt.date.fromisoformat(date + {4: '-01-01', 7: '-01', 10: ''}[len(date)])
            except (ValueError, KeyError):
                errors.append(f'{uid}: invalid date_iso {date}')
        rel, target = u.get('relation_type', ''), u.get('related_unit_id', '')
        if rel not in RELTYPES:
            errors.append(f'{uid}: unknown relation type {rel}')
        if target and (target not in ids or target == uid):
            errors.append(f'{uid}: invalid relation target {target}')
        if target and rel in ('none', ''):
            errors.append(f'{uid}: relation target without type')
        if rel not in ('none', '') and not target:
            if u.get('relation_status') != 'uncertain' or not u.get('relation_note'):
                errors.append(f'{uid}: missing relation target; explicit uncertainty and note required')
    vocabs = {k: {r['value'] for r in read_csv(root / f'data/vocabularies/{k}.csv')} for k in CLASSIFIERS}
    keys = set()
    for r in hypotheses:
        uid, feature = r['unit_id'], r['feature']
        key = hypothesis_key(r)
        if r['decision'] != 'superseded':
            if key in keys:
                errors.append(f'{uid}: duplicate hypothesis {feature}')
            keys.add(key)
        if uid not in ids or feature not in FMAP or not r['value'] or not r['rule'] or not r['evidence']:
            errors.append(f'{uid}: incomplete or unknown hypothesis {feature}')
        decision = r['decision']
        if uid in ids and decision not in ('reject', 'superseded'):
            try:
                validate_anchor(r, next(u for u in units if u['unit_id'] == uid))
            except ValueError as exc:
                errors.append(f'{uid}: {exc}')
        if decision not in ('', 'accept', 'reject', 'reformulate', 'superseded'):
            errors.append(f'{uid}: invalid review decision {decision}')
        if decision in ('accept', 'reject', 'reformulate') and (not r['reviewer'] or not r['reviewed_at']):
            errors.append(f'{uid}: review requires reviewer and reviewed_at')
        if decision == 'reformulate' and not r['new_value'].strip():
            errors.append(f'{uid}: reformulation requires new_value')
        value = r['new_value'] if decision == 'reformulate' else r['value']
        if feature in vocabs and decision not in ('reject', 'superseded'):
            if any(v.strip() not in vocabs[feature] for v in value.split('|')):
                errors.append(f'{uid}: {feature} outside vocabulary: {value}')
    if errors:
        raise ValueError('\n'.join(errors))


def effective_rows(hypotheses):
    for r in hypotheses:
        if r['decision'] not in ('reject', 'superseded'):
            yield dict(r, value=r['new_value'] if r['decision'] == 'reformulate' else r['value'],
                       review_status='validated' if r['decision'] in ('accept', 'reformulate') else 'pending_expert_validation')


def project_units(source, hypotheses):
    """Project current editorial decisions without changing documentary readings."""
    result = copy.deepcopy(source)
    by_id = {}
    for r in effective_rows(hypotheses):
        by_id.setdefault(r['unit_id'], []).append(r)
    for u in result['units']:
        old_places = {p['name']: p for p in u.get('places', [])}
        u['hyp'], u['terms'], u['persons_hyp'], u['places'] = {}, {}, [], []
        u.setdefault('signatories', [])
        u.setdefault('reliability', 'F')
        for name in ('deontic', 'fiscal', 'monetary', 'institutions'):
            u['terms'][name] = []
        grouped = {}
        for r in by_id.get(u['unit_id'], []):
            grouped.setdefault(FMAP[r['feature']], []).append(r)
        # Keep curated source places on units without an active geography
        # hypothesis.  Projection should not erase documentary coordinates
        # merely because the analytical layer has no row for that unit.
        if 'geography' not in grouped:
            u['places'] = list(old_places.values())
        for field, rows in grouped.items():
            values = list(dict.fromkeys(r['value'] for r in rows))
            state = 'validated' if all(r['review_status'] == 'validated' for r in rows) else 'pending_expert_validation'
            if field in CLASSIFIERS:
                u['hyp'][field] = dict(value='|'.join(values), rule='; '.join(dict.fromkeys(r['rule'] for r in rows)),
                                      ev=' / '.join(dict.fromkeys(r['evidence'] for r in rows)),
                                      status=state, evidence=rows)
            elif field == 'geography':
                for value in values:
                    occurrences = [r for r in rows if r['value'] == value]
                    row = occurrences[0]
                    place = copy.deepcopy(old_places.get(value, {'name': value, 'lat': None, 'lon': None, 'approx': True}))
                    place.update(ev=row['evidence'], rule=row['rule'], evidence=occurrences,
                                 status='validated' if all(r['review_status'] == 'validated' for r in occurrences)
                                 else 'pending_expert_validation')
                    u['places'].append(place)
            elif field == 'actors':
                u['persons_hyp'] = [dict(name=r['value'], ev=r['evidence'], status=r['review_status']) for r in rows]
            elif field in ('fiscal_terms', 'deontic_formulas', 'institutional_terms', 'monetary_expressions'):
                key = {'fiscal_terms': 'fiscal', 'deontic_formulas': 'deontic', 'institutional_terms': 'institutions', 'monetary_expressions': 'monetary'}[field]
                u['terms'][key] = [dict(t=r['value'], ev=r['evidence'], status=r['review_status']) for r in rows]
    return result


def derive(root, source=None, hypotheses=None):
    if source is None:
        source, hypotheses = load_sources(root)
    validate_sources(root, source, hypotheses)
    payload = project_units(source, hypotheses)
    units = payload['units']
    quality = audit_transcriptions(units)
    ner = extract_corpus(source['units'], EntityRecognizer(root / 'data/ner/authorities.json'))
    reasoning = extract_reasoning(source['units'], ner['candidates'])
    opinion_frames = extract_opinion_frames(source['units'])
    qualified = build_qualified_opinions(source['units'], root / 'data/source/qualified_opinions.json')
    contexts = build_contexts(source['units'], ner['candidates'], root / 'data/ner/reconciliations.json')
    covered = {int(s[:-1]) for u in units for s in u['folio_sides']}
    foliation_unreconciled = source.get('meta', {}).get('foliation_review', {}).get('status') == 'unreconciled'
    reference_system = 'legacy_working_references' if foliation_unreconciled else 'folio_sides'
    reference_coverage = dict(reference_system=reference_system, covered_numbers=len(covered),
                              extent=TOTAL, ratio=f'{len(covered)}/{TOTAL}',
                              percent=round(100 * len(covered) / TOTAL, 2))
    gaps = []
    f = 1
    while f <= TOTAL:
        if f in covered:
            f += 1
            continue
        start = f
        while f <= TOTAL and f not in covered:
            f += 1
        gaps.append(dict(unit_id=f'R142_G{len(gaps)+1:03d}', folio_start=str(start), folio_end=str(f-1),
                         carte=f-start, status='not_transcribed', reference_system=reference_system))
    meta = payload.setdefault('meta', {})
    # Keep the published count as a historical claim, separate from the calculation.
    meta.setdefault('coverage_reported', source.get('meta', {}).get('coverage_carte', ''))
    meta.update(n_units=len(units), n_manual=sum(u['transcription_status'].startswith('manual') for u in units),
                n_regest=sum(u['transcription_status'] == 'regest' for u in units), n_gap_rows=len(gaps),
                coverage_carte=f'{len(covered)}/{TOTAL}', coverage_folios=len(covered), total_folios=TOTAL,
                coverage_percent=round(100 * len(covered) / TOTAL, 2), n_hypotheses=len(hypotheses))
    meta['reference_coverage'] = reference_coverage
    meta['coverage_status'] = 'unreconciled_foliation' if foliation_unreconciled else 'computed_from_folio_sides'
    if foliation_unreconciled:
        # Do not expose a percentage with an unverified numerator and denominator.
        meta.update(coverage_carte=None, coverage_folios=None, total_folios=None, coverage_percent=None)
    documentary = []
    for u in units:
        r = {k: u.get(k, '') for k in DOC_COLS}
        r.update(marginal_note_present=u.get('marginal_note_present') or ('present' if u.get('marginal_note_raw') else 'not_checked'),
                 signatories_norm=u.get('signatories_norm', ''),
                 signatories_complete=u.get('signatories_complete', 'not_checked'),
                 transcription_status='manual_full' if u['transcription_status'] == 'manual' else u['transcription_status'],
                 relation_type='' if u.get('relation_type') == 'none' else u.get('relation_type', ''),
                 uncertain_readings=(u.get('text_diplomatic') or '').count('(?)'))
        r['relation_status'] = u.get('relation_status') or ('uncertain' if r['relation_type'] else 'not_applicable')
        documentary.append(r)
    for gap in gaps:
        documentary.append(dict(gap, register_id='ASVe_CSM_142', transcription_status='not_transcribed',
                                marginal_note_present='not_applicable', signatories_complete='not_applicable',
                                relation_status='not_applicable'))
    documentary.sort(key=lambda r: (int(re.match(r'\d+', r['folio_start'])[0]) if re.match(r'\d+', r['folio_start']) else TOTAL + 1, r['unit_id']))
    effective = list(effective_rows(hypotheses))
    analytical = []
    for u in units:
        row = {'unit_id': u['unit_id']}
        for field in FEATURES:
            entries = [r for r in effective if r['unit_id'] == u['unit_id'] and FMAP[r['feature']] == field]
            approved = entries and all(r['review_status'] == 'validated' for r in entries)
            row[field] = '|'.join(dict.fromkeys(r['value'] for r in entries))
            row[field + '_status'] = 'present' if approved else 'uncertain' if entries else 'not_checked'
            row[field + '_review_status'] = 'validated' if approved else 'pending_expert_validation' if entries else 'not_checked'
        analytical.append(row)
    slim = [dict(u=r['unit_id'], f=FMAP[r['feature']], v=r['value'], r=r['rule'], c=r['confidence'],
                 e=r['evidence'], status=r['review_status']) for r in effective]
    issues = []
    if foliation_unreconciled:
        issues.append(dict(id='foliation-concordance', status='unreconciled',
                           detail=source['meta']['foliation_review']['note']))
    elif meta['coverage_reported'] != meta['coverage_carte']:
        issues.append(dict(id='coverage-reconciliation', status='needs_expert_review',
                           detail=f"Published metadata: {meta['coverage_reported']}; explicit folio_sides: {meta['coverage_carte']}. No missing folio inferred."))
    for u in units:
        if not u.get('folio_sides'):
            issues.append(dict(id=u['unit_id'] + '-foliation', status='needs_expert_review', detail=u['foliation_note']))
        if u.get('relation_type') not in ('none', '', None) and not u.get('related_unit_id'):
            issues.append(dict(id=u['unit_id'] + '-relation', status='needs_expert_review', detail=u['relation_note']))
    manifest = dict(schema_version=2, source_version=source['meta'].get('version'),
                    documentary_units=len(units), gap_rows=len(gaps),
                    covered_folios=meta['coverage_folios'], total_folios=meta['total_folios'],
                    coverage_status=meta['coverage_status'], reference_coverage=reference_coverage,
                    hypothesis_rows=len(hypotheses), active_hypotheses=len(effective), editorial_issues=issues,
                    transcription_quality=quality['summary'],
                    ner_candidates=ner['summary'], ner_extractor=ner['extractor'],
                    ner_authority_sha256=ner['authority_sha256'],
                    entity_context=contexts['summary'],
                    reasoning=reasoning['summary'], reasoning_extractor=reasoning['extractor'],
                    reasoning_rules_sha256=reasoning['rules_sha256'],
                    opinion_frames=opinion_frames['summary'], opinion_frames_extractor=opinion_frames['extractor'],
                    opinion_frames_rules_sha256=opinion_frames['rules_sha256'],
                    qualified_opinions=qualified['summary'], qualified_opinions_sha256=qualified['source_sha256'],
                    entity_research_sha256=contexts['research_sha256'],
                    source_sha256={'units': hashlib.sha256(json_bytes(source)).hexdigest(),
                                   'hypotheses': hashlib.sha256(csv_bytes(hypotheses, HYP_COLS)).hexdigest()})
    provenance = f'''# Dataset provenance\n\nCanonical inputs: `data/source/units.json` and `data/source/hypotheses.csv`.\nSource version: {source['meta'].get('version')}. Build: `python3 scripts/pipeline.py build`.\n\n- Documentary units: {len(units)}; explicit gap ranges: {len(gaps)}.\n- Minimum reproducible coverage: {len(covered)}/{TOTAL} folios ({meta['coverage_percent']}%), counting unique folio numbers in `folio_sides`, not recto/verso sides or transcription completeness.\n- Manual text: {sum(bool(u.get('text_diplomatic')) for u in units)} units. Regests and HTR remain separate.\n- Unlocalized units: {sum(not u['folio_sides'] for u in units)}. Gap ranges are provisional complements of the localized units, not proof of missing source material.
- Hypotheses: {len(hypotheses)} recorded, {len(effective)} active. Rejected and superseded records remain in the source audit table.\n- The seven uncertainty states are distinct from editorial review status. A populated field is validated only when all its active hypotheses have been reviewed.\n- `data/` holds the dataset files; `docs/data/` holds the same files plus the ones the site loads. `release.json` records source hashes.\n\n## Open editorial questions\n\n'''
    marker = f"- Manual text: {sum(bool(u.get('text_diplomatic')) for u in units)} units. Regests and HTR remain separate."
    if foliation_unreconciled:
        old_line = f"- Minimum reproducible coverage: {len(covered)}/{TOTAL} folios ({meta['coverage_percent']}%), counting unique folio numbers in `folio_sides`, not recto/verso sides or transcription completeness."
        new_line = (f"- Legacy working index: {len(covered)}/{TOTAL} distinct reference numbers. "
                    "This is not archival coverage: digitisation labels and manuscript foliation diverge, "
                    "and the physical total is unknown. Archival coverage fields are null; "
                    "the reproducible old calculation is retained in `reference_coverage`.")
        provenance = provenance.replace(old_line, new_line)
        provenance = provenance.replace('Gap ranges are provisional complements of the localized units, not proof of missing source material.',
                                        'Gap ranges complement the legacy working references; they establish neither missing responses nor missing source material.')
    qa_line = (f'- Transcription QA: {quality["summary"]["flagged_units"]} units need review '
               f'({quality["summary"]["high_priority_units"]} high priority); '
               f'{quality["summary"]["evaluated_units"]} have CER/WER metrics. '
               'This is automated triage, not philological certification.')
    provenance = provenance.replace(marker, marker + '\n' + qa_line)
    provenance += '\n'.join('- ' + issue['detail'] for issue in issues) + '\n'
    provenance += '\nThe EADH 2026 paper reports 61 units and approximately 51% coverage. This historical claim is retained; reconciliation requires a foliation audit, not a silent data correction.\n'
    common = {'documentary.csv': csv_bytes(documentary, DOC_COLS), 'analytical.csv': csv_bytes(analytical, ANA_COLS),
              'units.json': json_bytes(payload), 'units.js': js_bytes('RISPOSTE', payload),
              'gaps.js': js_bytes('GAPS', gaps), 'hypo.js': js_bytes('HYPO', slim),
              'review.js': js_bytes('HYPOTHESES', hypotheses),
              'ner_candidates.json': json_bytes(ner), 'ner_candidates.js': js_bytes('NER_CANDIDATES', ner),
              'entity_context.json': json_bytes(contexts), 'entity_context.js': js_bytes('ENTITY_CONTEXT', contexts),
              'reasoning.json': json_bytes(reasoning), 'reasoning.js': js_bytes('REASONING', reasoning),
              'opinion_frames.json': json_bytes(opinion_frames), 'opinion_frames.js': js_bytes('OPINION_FRAMES', opinion_frames),
              'qualified_opinions.json': json_bytes(qualified), 'qualified_opinions.js': js_bytes('QUALIFIED_OPINIONS', qualified),
              'ner_candidates.csv': csv_bytes(ner['candidates'], ['candidate_id', 'unit_id', 'label', 'feature', 'value', 'surface', 'source_field', 'span_start', 'span_end', 'evidence', 'rule', 'status', 'normalization_status', 'source_sha256', 'extractor', 'authority_sha256']),
              'transcription_quality.json': json_bytes(quality),
              'transcription_quality.js': js_bytes('TRANSCRIPTION_QUALITY', quality),
              'hypotheses.csv': csv_bytes(hypotheses, HYP_COLS), 'PROVENANCE.md': provenance.encode(),
              'release.json': json_bytes(manifest), 'SCHEMA.md': (root / 'data/SCHEMA.md').read_bytes()}
    archive = io.BytesIO()
    bundle = {name: common[name] for name in DATASET_FILES if name in common}
    for extra in DATASET_FILES:
        if extra not in bundle and (root / 'docs/data' / extra).exists():
            bundle[extra] = (root / 'docs/data' / extra).read_bytes()
    with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_STORED) as zipped:
        for name, body in sorted(bundle.items()):
            zipped.writestr(zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0)), body)
    common['downloads/risposte-reg142-current.zip'] = archive.getvalue()
    # docs/data/ carries everything the site loads; data/ carries the dataset only.
    files = {f'docs/data/{name}': body for name, body in common.items()}
    files.update({f'data/{name}': body for name, body in common.items() if name in DATASET_FILES})
    files['data/downloads/risposte-reg142-current.zip'] = common['downloads/risposte-reg142-current.zip']
    for p in (root / 'docs/data').rglob('*'):
        rel = str(p.relative_to(root / 'docs/data'))
        if p.is_file() and rel not in common and rel in DATASET_FILES:
            files['data/' + rel] = p.read_bytes()
    from build_translations import render as render_translations
    files.update(render_translations(root, qualified['documents']))
    return files, manifest


def publish(root, files):
    """Validate before calling. Roll back all replaced files on Python exceptions.

    Per-file replacement is atomic; concurrent writers and power-loss recovery
    require an external transaction boundary (e.g. a reviewed Git commit).
    """
    files = {name: body for name, body in files.items()
             if not (root / name).exists() or (root / name).read_bytes() != body}
    previous = {name: (root / name).read_bytes() if (root / name).exists() else None for name in files}
    replaced = []
    with tempfile.TemporaryDirectory(prefix='.risposte-build-', dir=root) as temp:
        staging = Path(temp)
        for name, body in files.items():
            path = staging / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(body)
        try:
            for name in files:
                target = root / name
                target.parent.mkdir(parents=True, exist_ok=True)
                os.replace(staging / name, target)
                replaced.append(name)
        except BaseException:
            for name in reversed(replaced):
                target = root / name
                if previous[name] is None:
                    target.unlink(missing_ok=True)
                else:
                    target.write_bytes(previous[name])
            raise


def check(root):
    files, manifest = derive(root)
    stale = [name for name, body in files.items() if not (root / name).exists() or (root / name).read_bytes() != body]
    if stale:
        raise ValueError('Generated files differ from canonical inputs; run build:\n' + '\n'.join(stale))
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['build', 'check'])
    args = parser.parse_args()
    try:
        if args.command == 'build':
            files, manifest = derive(ROOT)
            publish(ROOT, files)
        else:
            manifest = check(ROOT)
        print(f"OK: {manifest['documentary_units']} units, {manifest['gap_rows']} reference gap ranges; "
              f"reference count {manifest['reference_coverage']['ratio']}; coverage status {manifest['coverage_status']}")
        for issue in manifest['editorial_issues']:
            print('EDITORIAL:', issue['detail'])
    except (ValueError, KeyError, OSError) as exc:
        parser.exit(1, str(exc) + '\n')


if __name__ == '__main__':
    main()
